-- Northwind Database for PostgreSQL
-- Converted from SQL Server version
-- This script does not create a database.
-- Run this script in the database you want the objects to be created.

drop function if exists ten_most_expensive_products() cascade;
drop function if exists employee_sales_by_country(timestamp, timestamp) cascade;
drop function if exists sales_by_year(timestamp, timestamp) cascade;
drop function if exists cust_orders_detail(integer) cascade;
drop function if exists cust_orders_orders(char) cascade;
drop function if exists cust_order_hist(char) cascade;
drop function if exists sales_by_category(varchar, varchar) cascade;

DROP VIEW IF EXISTS category_sales_for_1997 CASCADE;
DROP VIEW IF EXISTS sales_by_category CASCADE;
DROP VIEW IF EXISTS sales_totals_by_amount CASCADE;
DROP VIEW IF EXISTS summary_of_sales_by_quarter CASCADE;
DROP VIEW IF EXISTS summary_of_sales_by_year CASCADE;
DROP VIEW IF EXISTS invoices CASCADE;
DROP VIEW IF EXISTS order_details_extended CASCADE;
DROP VIEW IF EXISTS order_subtotals CASCADE;
DROP VIEW IF EXISTS product_sales_for_1997 CASCADE;
DROP VIEW IF EXISTS alphabetical_list_of_products CASCADE;
DROP VIEW IF EXISTS current_product_list CASCADE;
DROP VIEW IF EXISTS orders_qry CASCADE;
DROP VIEW IF EXISTS products_above_average_price CASCADE;
DROP VIEW IF EXISTS products_by_category CASCADE;
DROP VIEW IF EXISTS quarterly_orders CASCADE;
DROP VIEW IF EXISTS customer_and_suppliers_by_city CASCADE;

DROP TABLE IF EXISTS order_details CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS shippers CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS territories CASCADE;
DROP TABLE IF EXISTS region CASCADE;
DROP TABLE IF EXISTS customer_demographics CASCADE;
DROP TABLE IF EXISTS customer_customer_demo CASCADE;
DROP TABLE IF EXISTS employee_territories CASCADE;

drop sequence if exists employees_employee_id_seq cascade;
drop sequence if exists categories_category_id_seq cascade;
drop sequence if exists shippers_shipper_id_seq cascade;
drop sequence if exists suppliers_supplier_id_seq cascade;
drop sequence if exists orders_order_id_seq cascade;
drop sequence if exists products_product_id_seq cascade;



CREATE TABLE employees (
	employee_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
	last_name varchar (20) NOT NULL ,
	first_name varchar (10) NOT NULL ,
	title varchar (30) NULL ,
	title_of_courtesy varchar (25) NULL ,
	birth_date timestamp NULL ,
	hire_date timestamp NULL ,
	address varchar (60) NULL ,
	city varchar (15) NULL ,
	region varchar (15) NULL ,
	postal_code varchar (10) NULL ,
	country varchar (15) NULL ,
	home_phone varchar (24) NULL ,
	extension varchar (4) NULL ,
	photo bytea NULL ,
	notes text NULL ,
	reports_to integer NULL ,
	photo_path varchar (255) NULL ,
	CONSTRAINT pk_employees PRIMARY KEY 
	(
		employee_id
	),
	CONSTRAINT ck_birthdate CHECK (birth_date < CURRENT_TIMESTAMP)
);
 CREATE  INDEX ix_employee_last_name ON employees(last_name);
 CREATE  INDEX ix_employee_postal_code ON employees(postal_code);

CREATE TABLE categories (
	category_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
	category_name varchar (15) NOT NULL ,
	description text NULL ,
	picture bytea NULL ,
	CONSTRAINT pk_categories PRIMARY KEY 
	(
		category_id
	)
);
 CREATE  INDEX category_name ON categories(category_name);

CREATE TABLE customers (
	customer_id char (5) NOT NULL ,
	company_name varchar (40) NOT NULL ,
	contact_name varchar (30) NULL ,
	contact_title varchar (30) NULL ,
	address varchar (60) NULL ,
	city varchar (15) NULL ,
	region varchar (15) NULL ,
	postal_code varchar (10) NULL ,
	country varchar (15) NULL ,
	phone varchar (24) NULL ,
	fax varchar (24) NULL ,
	CONSTRAINT pk_customers PRIMARY KEY 
	(
		customer_id
	)
);
 CREATE  INDEX ix_customers_city ON customers(city);
 CREATE  INDEX ix_customers_company_name ON customers(company_name);
 CREATE  INDEX ix_customers_postal_code ON customers(postal_code);
 CREATE  INDEX ix_customers_region ON customers(region);

CREATE TABLE shippers (
	shipper_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
	company_name varchar (40) NOT NULL ,
	phone varchar (24) NULL ,
	CONSTRAINT pk_shippers PRIMARY KEY 
	(
		shipper_id
	)
);
CREATE TABLE suppliers (
	supplier_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
	company_name varchar (40) NOT NULL ,
	contact_name varchar (30) NULL ,
	contact_title varchar (30) NULL ,
	address varchar (60) NULL ,
	city varchar (15) NULL ,
	region varchar (15) NULL ,
	postal_code varchar (10) NULL ,
	country varchar (15) NULL ,
	phone varchar (24) NULL ,
	fax varchar (24) NULL ,
	home_page text NULL ,
	CONSTRAINT pk_suppliers PRIMARY KEY 
	(
		supplier_id
	)
);
 CREATE  INDEX ix_suppliers_company_name ON suppliers(company_name);
 CREATE  INDEX ix_suppliers_postal_code ON suppliers(postal_code);

CREATE TABLE orders (
	order_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
	customer_id char (5) NULL ,
	employee_id integer NULL ,
	order_date timestamp NULL ,
	required_date timestamp NULL ,
	shipped_date timestamp NULL ,
	ship_via integer NULL ,
	freight numeric(19,4) NULL DEFAULT (0),
	ship_name varchar (40) NULL ,
	ship_address varchar (60) NULL ,
	ship_city varchar (15) NULL ,
	ship_region varchar (15) NULL ,
	ship_postal_code varchar (10) NULL ,
	ship_country varchar (15) NULL ,
	CONSTRAINT pk_orders PRIMARY KEY 
	(
		order_id
	)
);
 CREATE  INDEX ix_orders_customer_id ON orders(customer_id);
 CREATE  INDEX ix_orders_customers_orders ON orders(customer_id);
 CREATE  INDEX ix_orders_employee_id ON orders(employee_id);
 CREATE  INDEX ix_orders_employees_orders ON orders(employee_id);
 CREATE  INDEX ix_orders_order_date ON orders(order_date);
 CREATE  INDEX ix_orders_shipped_date ON orders(shipped_date);
 CREATE  INDEX ix_orders_shippers_orders ON orders(ship_via);
 CREATE  INDEX ix_orders_ship_postal_code ON orders(ship_postal_code);

CREATE TABLE products (
	product_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
	product_name varchar (40) NOT NULL ,
	supplier_id integer NULL ,
	category_id integer NULL ,
	quantity_per_unit varchar (20) NULL ,
	unit_price numeric(19,4) NULL DEFAULT (0),
	units_in_stock smallint NULL DEFAULT (0),
	units_on_order smallint NULL DEFAULT (0),
	reorder_level smallint NULL DEFAULT (0),
	discontinued boolean NOT NULL DEFAULT FALSE,
	CONSTRAINT pk_products PRIMARY KEY 
	(
		product_id
	),
	CONSTRAINT fk_products_categories FOREIGN KEY 
	(
		category_id
	) REFERENCES categories (
		category_id
	),
	CONSTRAINT fk_products_suppliers FOREIGN KEY 
	(
		supplier_id
	) REFERENCES suppliers (
		supplier_id
	),
	CONSTRAINT ck_products_unit_price CHECK (unit_price >= 0),
	CONSTRAINT ck_reorder_level CHECK (reorder_level >= 0),
	CONSTRAINT ck_units_in_stock CHECK (units_in_stock >= 0),
	CONSTRAINT ck_units_on_order CHECK (units_on_order >= 0)
);
 CREATE  INDEX ix_products_categories_products ON products(category_id);
 CREATE  INDEX ix_products_category_id ON products(category_id);
 CREATE  INDEX ix_products_product_name ON products(product_name);
 CREATE  INDEX ix_products_supplier_id ON products(supplier_id);
 CREATE  INDEX ix_products_suppliers_products ON products(supplier_id);

CREATE TABLE order_details (
	order_id integer NOT NULL ,
	product_id integer NOT NULL ,
	unit_price numeric(19,4) NOT NULL DEFAULT (0),
	quantity smallint NOT NULL DEFAULT (1),
	discount real NOT NULL DEFAULT (0),
	CONSTRAINT pk_order_details PRIMARY KEY 
	(
		order_id,
		product_id
	),
	CONSTRAINT ck_discount CHECK (discount >= 0 and (discount <= 1)),
	CONSTRAINT ck_quantity CHECK (quantity > 0),
	CONSTRAINT ck_unit_price CHECK (unit_price >= 0)
);
 CREATE  INDEX ix_order_details_order_id ON order_details(order_id);
 CREATE  INDEX ix_order_product_id ON order_details(product_id);
 CREATE  INDEX ix_order_products_order_details ON order_details(product_id);

CREATE OR REPLACE VIEW customer_and_suppliers_by_city AS
SELECT city, company_name, contact_name, 'Customers' AS relationship
FROM customers
UNION SELECT city, company_name, contact_name, 'Suppliers'
FROM suppliers;
--ORDER BY City, CompanyName

CREATE OR REPLACE VIEW alphabetical_list_of_products AS
SELECT products.*, categories.category_name
FROM categories INNER JOIN products ON categories.category_id = products.category_id
WHERE (((products.discontinued)=false));

CREATE OR REPLACE VIEW current_product_list AS
SELECT product_list.product_id, product_list.product_name
FROM products AS product_list
WHERE (((product_list.discontinued)=false));
--ORDER BY Product_List.ProductName

CREATE OR REPLACE VIEW orders_qry AS
SELECT orders.order_id, orders.customer_id, orders.employee_id, orders.order_date, orders.required_date, 
	orders.shipped_date, orders.ship_via, orders.freight, orders.ship_name, orders.ship_address, orders.ship_city, 
	orders.ship_region, orders.ship_postal_code, orders.ship_country, 
	customers.company_name, customers.address, customers.city, customers.region, customers.postal_code, customers.country
FROM customers INNER JOIN orders ON customers.customer_id = orders.customer_id;

CREATE OR REPLACE VIEW products_above_average_price AS
SELECT products.product_name, products.unit_price
FROM products
WHERE products.unit_price>(SELECT AVG(unit_price) FROM products);
--ORDER BY Products.UnitPrice DESC

CREATE OR REPLACE VIEW products_by_category AS
SELECT categories.category_name, products.product_name, products.quantity_per_unit, products.units_in_stock, products.discontinued
FROM categories INNER JOIN products ON categories.category_id = products.category_id
WHERE products.discontinued = false;
--ORDER BY Categories.CategoryName, Products.ProductName

CREATE OR REPLACE VIEW quarterly_orders AS
SELECT DISTINCT customers.customer_id, customers.company_name, customers.city, customers.country
FROM customers RIGHT JOIN orders ON customers.customer_id = orders.customer_id
WHERE orders.order_date BETWEEN '19970101' AND '19971231';

CREATE OR REPLACE VIEW invoices AS
SELECT orders.ship_name, orders.ship_address, orders.ship_city, orders.ship_region, orders.ship_postal_code, 
	orders.ship_country, orders.customer_id, customers.company_name AS customer_name, customers.address, customers.city, 
	customers.region, customers.postal_code, customers.country, 
	(employees.first_name || ' ' || employees.last_name) AS salesperson, 
	orders.order_id, orders.order_date, orders.required_date, orders.shipped_date, shippers.company_name AS shipper_name, 
	order_details.product_id, products.product_name, order_details.unit_price, order_details.quantity, 
	order_details.discount, 
	(((order_details.unit_price*quantity*(1-discount)/100))*100) AS extended_price, orders.freight
FROM 	shippers INNER JOIN 
		(products INNER JOIN 
			(
				(employees INNER JOIN 
					(customers INNER JOIN orders ON customers.customer_id = orders.customer_id) 
				ON employees.employee_id = orders.employee_id) 
			INNER JOIN order_details ON orders.order_id = order_details.order_id) 
		ON products.product_id = order_details.product_id) 
	ON shippers.shipper_id = orders.ship_via;

CREATE OR REPLACE VIEW order_details_extended AS
SELECT order_details.order_id, order_details.product_id, products.product_name, 
	order_details.unit_price, order_details.quantity, order_details.discount, 
	(((order_details.unit_price*quantity*(1-discount)/100))*100) AS extended_price
FROM products INNER JOIN order_details ON products.product_id = order_details.product_id;
--ORDER BY "Order Details".OrderID

CREATE OR REPLACE VIEW order_subtotals AS
SELECT order_details.order_id, SUM(((order_details.unit_price*quantity*(1-discount)/100))*100) AS subtotal
FROM order_details
GROUP BY order_details.order_id;

CREATE OR REPLACE VIEW product_sales_for_1997 AS
SELECT categories.category_name, products.product_name, 
SUM(((order_details.unit_price*quantity*(1-discount)/100))*100) AS product_sales
FROM (categories INNER JOIN products ON categories.category_id = products.category_id) 
	INNER JOIN (orders 
		INNER JOIN order_details ON orders.order_id = order_details.order_id) 
	ON products.product_id = order_details.product_id
WHERE (((orders.shipped_date) BETWEEN '19970101' AND '19971231'))
GROUP BY categories.category_name, products.product_name;

CREATE OR REPLACE VIEW category_sales_for_1997 AS
SELECT product_sales_for_1997.category_name, SUM(product_sales_for_1997.product_sales) AS category_sales
FROM product_sales_for_1997
GROUP BY product_sales_for_1997.category_name;

CREATE OR REPLACE VIEW sales_by_category AS
SELECT categories.category_id, categories.category_name, products.product_name, 
	SUM(order_details_extended.extended_price) AS product_sales
FROM 	categories INNER JOIN 
		(products INNER JOIN 
			(orders INNER JOIN order_details_extended ON orders.order_id = order_details_extended.order_id) 
		ON products.product_id = order_details_extended.product_id) 
	ON categories.category_id = products.category_id
WHERE orders.order_date BETWEEN '19970101' AND '19971231'
GROUP BY categories.category_id, categories.category_name, products.product_name;
--ORDER BY Products.ProductName

CREATE OR REPLACE VIEW sales_totals_by_amount AS
SELECT order_subtotals.subtotal AS sale_amount, orders.order_id, customers.company_name, orders.shipped_date
FROM 	customers INNER JOIN 
		(orders INNER JOIN order_subtotals ON orders.order_id = order_subtotals.order_id) 
	ON customers.customer_id = orders.customer_id
WHERE (order_subtotals.subtotal > 2500) AND (orders.shipped_date BETWEEN '19970101' AND '19971231');

CREATE OR REPLACE VIEW summary_of_sales_by_quarter AS
SELECT orders.shipped_date, orders.order_id, order_subtotals.subtotal
FROM orders INNER JOIN order_subtotals ON orders.order_id = order_subtotals.order_id
WHERE orders.shipped_date IS NOT NULL;
--ORDER BY Orders.ShippedDate

CREATE OR REPLACE VIEW summary_of_sales_by_year AS
SELECT orders.shipped_date, orders.order_id, order_subtotals.subtotal
FROM orders INNER JOIN order_subtotals ON orders.order_id = order_subtotals.order_id
WHERE orders.shipped_date IS NOT NULL;
--ORDER BY Orders.ShippedDate

CREATE OR REPLACE FUNCTION ten_most_expensive_products()
RETURNS SETOF RECORD AS $$
BEGIN
  RETURN QUERY
  SELECT products.product_name AS ten_most_expensive_products, products.unit_price
  FROM products
  ORDER BY products.unit_price DESC
  LIMIT 10;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION employee_sales_by_country(p_beginning_date timestamp, p_ending_date timestamp)
RETURNS SETOF RECORD AS $$
BEGIN
  RETURN QUERY
  SELECT employees.country, employees.last_name, employees.first_name, orders.shipped_date, orders.order_id, order_subtotals.subtotal AS sale_amount
  FROM employees INNER JOIN 
  	(orders INNER JOIN order_subtotals ON orders.order_id = order_subtotals.order_id) 
  	ON employees.employee_id = orders.employee_id
  WHERE orders.shipped_date BETWEEN p_beginning_date AND p_ending_date;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION sales_by_year(p_beginning_date timestamp, p_ending_date timestamp)
RETURNS SETOF RECORD AS $$
BEGIN
  RETURN QUERY
  SELECT orders.shipped_date, orders.order_id, order_subtotals.subtotal, EXTRACT(YEAR FROM shipped_date)::text AS year
  FROM orders INNER JOIN order_subtotals ON orders.order_id = order_subtotals.order_id
  WHERE orders.shipped_date BETWEEN p_beginning_date AND p_ending_date;
END;
$$ LANGUAGE plpgsql;


/* The following adds stored procedures */

DROP PROCEDURE IF EXISTS cust_orders_detail CASCADE;

CREATE OR REPLACE FUNCTION cust_orders_detail(p_orderid integer)
RETURNS SETOF RECORD AS $$
BEGIN
  RETURN QUERY
  SELECT product_name,
      ROUND(Od.unit_price, 2) AS unit_price,
      quantity,
      (discount * 100)::integer AS discount,
      ROUND(quantity * (1 - discount) * Od.unit_price, 2) AS extended_price
  FROM products P, order_details Od
  WHERE Od.product_id = P.product_id AND Od.order_id = p_orderid;
END;
$$ LANGUAGE plpgsql;



DROP PROCEDURE IF EXISTS cust_orders_orders CASCADE;

CREATE OR REPLACE FUNCTION cust_orders_orders(p_customerid char(5))
RETURNS SETOF RECORD AS $$
BEGIN
  RETURN QUERY
  SELECT order_id, 
  	order_date,
  	required_date,
  	shipped_date
  FROM orders
  WHERE customer_id = p_customerid
  ORDER BY order_id;
END;
$$ LANGUAGE plpgsql;



DROP PROCEDURE IF EXISTS cust_order_hist CASCADE;
CREATE OR REPLACE FUNCTION cust_order_hist(p_customerid char(5))
RETURNS SETOF RECORD AS $$
BEGIN
  RETURN QUERY
  SELECT product_name, SUM(quantity)
  FROM products P, order_details OD, orders O, customers C
  WHERE C.customer_id = p_customerid
  AND C.customer_id = O.customer_id AND O.order_id = OD.order_id AND OD.product_id = P.product_id
  GROUP BY product_name;
END;
$$ LANGUAGE plpgsql;


DROP PROCEDURE IF EXISTS sales_by_category CASCADE;
CREATE OR REPLACE FUNCTION sales_by_category(p_categoryname varchar(15), p_ordyear varchar(4) DEFAULT '1998')
RETURNS SETOF RECORD AS $$
BEGIN
  IF p_ordyear != '1996' AND p_ordyear != '1997' AND p_ordyear != '1998' THEN
    p_ordyear := '1998';
  END IF;

  RETURN QUERY
  SELECT product_name,
  	ROUND(SUM((OD.quantity * (1-OD.discount))::decimal(14,2) * OD.unit_price), 0) AS total_purchase
  FROM order_details OD, orders O, products P, categories C
  WHERE OD.order_id = O.order_id
  	AND OD.product_id = P.product_id
  	AND P.category_id = C.category_id
  	AND C.category_name = p_categoryname
  	AND EXTRACT(YEAR FROM O.order_date)::text = p_ordyear
  GROUP BY product_name
  ORDER BY product_name;
END;
$$ LANGUAGE plpgsql;


CREATE TABLE customer_customer_demo
	(customer_id char(5) NOT NULL,
	customer_type_id char(10) NOT NULL
);

CREATE TABLE customer_demographics 
	(customer_type_id char(10) NOT NULL ,
	customer_desc text NULL
);
	
CREATE TABLE region 
	( region_id int NOT NULL ,
	region_description char(50) NOT NULL
);

CREATE TABLE territories 
	(territory_id varchar(20) NOT NULL ,
	territory_description char(50) NOT NULL ,
        region_id int NOT NULL
);

CREATE TABLE employee_territories 
	(employee_id int NOT NULL,
	territory_id varchar(20) NOT NULL
);
